DROP TABLE IF EXISTS copy;

CREATE TABLE copy (
  ID IDENTITY PRIMARY KEY,
  MACHINE_IP VARCHAR (20) NOT NULL,
  CONTENT VARCHAR(255) NOT NULL,
  USER_ID VARCHAR(50) NOT NULL
);

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  username VARCHAR (20) PRIMARY KEY,
  password VARCHAR (20) NOT NULL,
  role VARCHAR(255) NOT NULL
);